apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask_api_deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: DOCKER_IMAGE_ID
          ports:
            - containerPort: 5000
