apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask_api_deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask_api
  template:
    metadata:
      labels:
        app: flask_api
    spec:
      containers:
        - name: flask_api
          image: 422476076098.dkr.ecr.us-west-1.amazonaws.com/flask_api_repo:latest
          ports:
            - containerPort: 5000
