version: "3.7"

services:
  helloworld:
    container_name: helloworld
    image: rocketbal/helloworld:latest
    build:
      context: ./
    ports:
      - 8080:8080
    env_file:
      - ./.env_file
